# -*- coding: utf-8 -*-
"""Postman task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LnhQJ8BFs9t2NzAotMZfJuQVuysJlguG
"""

import numpy as np
import pandas as pd
import seaborn as sns

from sklearn.datasets import load_iris

np.random.seed(0)
print("ready")

df = sns.load_dataset("iris")
df = df.dropna()
df.head()

#encoding species with numbers
from sklearn.preprocessing import LabelEncoder
le_species = LabelEncoder()
y = le_species.fit_transform(df["species"]).astype(int)


FEATURES = ["sepal_length","sepal_width","petal_length","petal_width"]
X = df[FEATURES].values.astype(float)


print(f"rows: {len(y)}")
df.head()
#print(df.to_string())

# Train and test split

def train_test_split(X, y, test_size=0.25, seed=0):
    rng = np.random.default_rng(seed)
    idx = rng.permutation(len(y))
    cut = int(len(y) * (1 - test_size))
    train, test = idx[:cut], idx[cut:]
    return X[train], X[test], y[train], y[test]

def accuracy(y_true, y_pred):
    return float(np.mean(y_true == y_pred))

X_train, X_test, y_train, y_test = train_test_split(X, y, seed=1)
print(f"train {len(y_train)}   test {len(y_test)}")
print(y_test)

#measuring gini impurity

def gini(y):
    if len(y) == 0:
        return 0.0
    _, counts = np.unique(y, return_counts=True)
    p = counts / len(y)
    return 1.0 - np.sum(p ** 2)

print(f"our training set  -> {gini(y_train):.3f}")
print("gini value is 0.666 as the probability of any species is 0.3")

def candidate_thresholds(column, max_candidates=20):
    vals = np.unique(column)
    if len(vals) <= max_candidates:
        return vals
    return np.unique(np.quantile(column, np.linspace(0.05, 0.95, max_candidates)))


def best_split(X, y, feature_subset=None):
    """Return (feature, threshold, gain) of the split that reduces Gini most."""
    n_samples, n_features = X.shape
    parent = gini(y)
    best_feature, best_threshold, best_score = None, None, parent

    features = range(n_features) if feature_subset is None else feature_subset
    for f in features:
        for t in candidate_thresholds(X[:, f]):
            left = X[:, f] <= t
            n_left = left.sum()
            if n_left == 0 or n_left == n_samples:
                continue
            score = (n_left * gini(y[left]) +
                     (n_samples - n_left) * gini(y[~left])) / n_samples
            if score < best_score:
                best_feature, best_threshold, best_score = f, t, score

    if best_feature is None:
        return None, None, 0.0
    return best_feature, best_threshold, parent - best_score


f, t, gain = best_split(X_train, y_train)
print(f"best first question: is {FEATURES[f]} <= {t}?")
print(f"gain: {gain:.4f}")

class Node:
    def __init__(self, **kw):
        self.__dict__.update(kw)


def majority(y):
    vals, counts = np.unique(y, return_counts=True)
    return vals[np.argmax(counts)]


def build_tree(X, y, depth=0, max_depth=6, min_samples_split=5,
               feature_subset_size=None):
    # --- stopping rules
    if (depth >= max_depth or len(y) < min_samples_split
            or len(np.unique(y)) == 1):
        return Node(leaf=True, prediction=majority(y), n=len(y))

    # (this argument does nothing yet -- you will use it for decision trees)
    subset = None
    if feature_subset_size is not None:
        subset = np.random.choice(X.shape[1], feature_subset_size, replace=False)

    f, t, gain = best_split(X, y, subset)
    if f is None:
        return Node(leaf=True, prediction=majority(y), n=len(y))

    mask = X[:, f] <= t
    return Node(leaf=False, feature=f, threshold=t, gain=gain, n=len(y),
                left=build_tree(X[mask], y[mask], depth + 1, max_depth,
                                min_samples_split, feature_subset_size),
                right=build_tree(X[~mask], y[~mask], depth + 1, max_depth,
                                 min_samples_split, feature_subset_size))


tree = build_tree(X_train, y_train, max_depth=4)
print("tree built")

def predict_one(node, x):
    while not node.leaf:
        node = node.left if x[node.feature] <= node.threshold else node.right
    return node.prediction


def predict(tree, X):
    return np.array([predict_one(tree, row) for row in X])


train_acc = accuracy(y_train, predict(tree, X_train))
test_acc = accuracy(y_test, predict(tree, X_test))
print(f"depth-4 tree   train {train_acc:.3f}   test {test_acc:.3f}")
print(f"baseline                       {1 - y_test.mean():.3f}")

PRETTY = {
    "sepal_length": "sepal length",
    "sepal_width": "sepal width",
    "petal_length": "petal length",
    "petal_width": "petal width"
}

def print_tree(node, indent="", branch=""):
    if node.leaf:
        verdict = "SURVIVED" if node.prediction == 1 else "DIED"
        print(f"{indent}{branch}-> {verdict}  (n={node.n})")
        return
    name = PRETTY[FEATURES[node.feature]]
    print(f"{indent}{branch}{name} <= {node.threshold:g} ?")
    print_tree(node.left,  indent + "   ", "yes: ")
    print_tree(node.right, indent + "   ", "no:  ")


print_tree(build_tree(X_train, y_train, max_depth=3, min_samples_split=10))

depths = [1, 2, 3, 4, 5, 6, 8, 10, 12, 16, 20]
train_scores, test_scores, leaf_counts = [], [], []


def count_leaves(node):
    return 1 if node.leaf else count_leaves(node.left) + count_leaves(node.right)


for d in depths:
    t_ = build_tree(X_train, y_train, max_depth=d, min_samples_split=2)
    train_scores.append(accuracy(y_train, predict(t_, X_train)))
    test_scores.append(accuracy(y_test, predict(t_, X_test)))
    leaf_counts.append(count_leaves(t_))
    print(f"depth {d:>2}   train {train_scores[-1]:.3f}   "
          f"test {test_scores[-1]:.3f}   leaves {leaf_counts[-1]:>3}")


def confusion_matrix(y_true, y_pred):
    cm = np.zeros((3, 3), dtype=int)
    for a, b in zip(y_true, y_pred):
        cm[a, b] += 1
    return cm


best_tree = build_tree(X_train, y_train, max_depth=4)
pred = predict(best_tree, X_test)
cm = confusion_matrix(y_test, pred)

print("TRUTH↓/PRED→   Species 1   Species 2  Species 3")
print(f"Species 1     {cm[0,0]:>6}     {cm[0,1]:>6}     {cm[0,2]:>6}")
print(f"Species 2     {cm[1,0]:>6}     {cm[1,1]:>6}     {cm[1,2]:>6}")
print(f"Species 3.    {cm[2,0]:>6}     {cm[2,1]:>6}     {cm[2,2]:>6}")
#tn, fp, fn, tp = cm.ravel()
aa , ab, ac,ba,bb,bc,ca,cb,cc = cm.ravel()
print(f"precision for Species 1 : {aa/(aa+ba+ca)}")
print(f"precision for Species 2 : {bb/(ab+bb+cb)}")
print(f"precision for Species 3 : {cc/(ac+bc+cc)}")

#print(f"\nprecision {tp/(tp+fp):.3f}   recall {tp/(tp+fn):.3f}")
